worlds:
  world:
    armorer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    butcher:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    cartographer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    cleric:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    farmer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    fisherman:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    fletcher:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    leatherworker:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    librarian:
      enabled: true
      search_radius: 5
      delay_ticks: 60
      min_level: 1
      max_level: 5
    mason:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    shepherd:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    toolsmith:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    weaponsmith:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5

  world_nether:
    armorer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    butcher:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    cartographer:
      enabled: true
      search_radius: 5
      delay_ticks: 60
      min_level: 1
      max_level: 5
    cleric:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    farmer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    fisherman:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    fletcher:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    leatherworker:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    librarian:
      enabled: true
      search_radius: 6
      delay_ticks: 60
      min_level: 1
      max_level: 5
    mason:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    shepherd:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    toolsmith:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    weaponsmith:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5

  world_the_end:
    armorer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    butcher:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    cartographer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    cleric:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    farmer:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    fisherman:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    fletcher:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    leatherworker:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    librarian:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    mason:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    shepherd:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    toolsmith:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
    weaponsmith:
      enabled: true
      search_radius: 3
      delay_ticks: 60
      min_level: 1
      max_level: 5
